version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: iris-app/Dockerfile
      target: final
    #restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 49187:52773
      - 53773
    volumes:
      - ./iris-app/:/home/irisowner/dev

  angular:
    init: true
    container_name: jrnindexer-ui
    build:
      context: .
      dockerfile: journal-indexer-ui/Dockerfile
    ports:
      - 14200:4200
    depends_on:
      - iris