version: '3.6'
services:
  iris:
    networks:
      indexer_net:
    build:
      context: .
      dockerfile: Dockerfile
    
    command: --check-caps false --ISCAgent false
    container_name: journal-indexer-iris
    ports:
      - 1972
      - 49187:52773
      #- 52773:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev

  angular:
    networks:
      indexer_net:
    build:
      context: front-end
      dockerfile: Dockerfile
    container_name: journal-indexer-ui
    volumes:
      - ./front-end/journal-indexer-ui.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8090:80
    depends_on:
      - iris

networks:
  indexer_net:
