Class dc.journalindexer.rest.model.Filter Extends (%RegisteredObject, %JSON.Adaptor) [ ProcedureBlock ]
{

Property Address As dc.journalindexer.rest.model.FilterProperties;

Property DatabaseName As dc.journalindexer.rest.model.FilterProperties;

Property File As dc.journalindexer.rest.model.FilterProperties;

Property GlobalName As dc.journalindexer.rest.model.FilterProperties;

Property InTransaction As dc.journalindexer.rest.model.FilterProperties;

Property NewValue As dc.journalindexer.rest.model.FilterProperties;

Property OldValue As dc.journalindexer.rest.model.FilterProperties;

Property ProcessID As dc.journalindexer.rest.model.FilterProperties;

Property Subscripts As list Of dc.journalindexer.rest.model.FilterProperties;

Property TimeStamp As dc.journalindexer.rest.model.FilterProperties;

Property Type As dc.journalindexer.rest.model.FilterProperties;

}
