Class dc.journalindexer.rest.model.Jrnrecord Extends %RegisteredObject [ ProcedureBlock ]
{

Property address As %Integer;

Property databaseName As %String;

Property existsNewValue As %Boolean;

Property existsOldValue As %Boolean;

Property file As %Integer;

Property formattedNewValue As %String;

Property formattedOldValue As %String;

Property globalNode As %String;

Property inTransaction As %Boolean;

Property nextAddress As %Integer;

Property position As %Integer;

Property prevAddress As %Integer;

Property processID As %Integer;

Property timestamp As %String;

Property type As %String;

}
